[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "battlemetrics"
description = "Battlemetrics API wrapper."
version = "1.0.2"
authors = [{ name = "Gnomeslayer", email = "declan.otten@live.com.au" }]
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
keywords = ["battlemetrics", "battlemetricsapi", "api", "gaming"]
dependencies = ["aiohttp==3.9.3"]
requires-python = ">=3.6"

[project.urls]
Homepage = "https://github.com/Gnomeslayer/battlemetrics"